stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - python manage.py test
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
  only:
    - main
